version: '3.8'

services:
  stremio-vlxx:
    build: .
    container_name: stremio-vlxx
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - NODE_ENV=production
