name: volpi_media
description: "VolPi Media - Ứng dụng xem Trực tiếp bóng đá, Anime Yumei và Phim lẻ cho Android TV, iPhone và iPad"
publish_to: 'none'
version: 1.0.9+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
